config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :looks
  devise_for :users
  root "looks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_and_belongs_to_many :looks
    validates :name, presence: true
    validates :name, uniqueness: true
end

app/models/look.rb
class Look < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  has_and_belongs_to_many :categories
  has_many :favorites
  has_many :ratings
  has_many :look_schedules

  validates :description, presence: true

  attr_accessor :category_names

  before_save :assign_categories

  private

  def assign_categories
    if category_names
      self.categories = category_names.split(',').map do |name|
        Category.find_or_create_by(name: name.strip)
      end
    end
  end
end

app/models/look_schedule.rb
class LookSchedule < ApplicationRecord
  belongs_to :user
  belongs_to :look

  validates :date, presence: true
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :look

  validates :score, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :looks
  has_many :favorites
  has_many :ratings
  has_many :look_schedules

  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @looks = Look.all
    @look = Look.new
  end
end

app/controllers/looks_controller.rb
class LooksController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @user = current_user
        @categories = Category.all
        if params[:category_names].present?
          @looks = Look.joins(:categories).where(categories: { name: params[:category_names].split(',').map(&:strip) }).distinct
        else
          @looks = Look.all
        end
    end
      
    def new
        @user = current_user
        @look = @user.looks.new
    end

    def show
        @look = Look.find(params[:id])
    end

    def create
        @user = current_user
        @look = @user.looks.new(look_params)
        @looks = Look.all
        respond_to do |format|
            if @look.save
                format.html { redirect_to looks_path }
                format.turbo_stream
            else
                format.html { render :new }
            end
        end
    end
    

    def destroy
        @look = Look.find(params[:id])
        @look.destroy
        redirect_to looks_path
    end

    def edit
        @look = Look.find(params[:id])
    end

    def update
        @look = Look.find(params[:id])
        if params[:look][:photos] == [""]
            params[:look].delete(:photos)
        end
        respond_to do |format|
            if @look.update!(look_params)
                format.html { redirect_to looks_path }
            else
                render :edit
            end
        end
    end

    private

    def look_params
        params.require(:look).permit(:description, :category_names, photos: [])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/looks_helper.rb
module LooksHelper
end

app/views/layouts/_nav.html.erb
<!-- component -->
<div class="fixed bottom-0 left-0 z-50 w-full h-16 bg-white border-t border-gray-200 dark:bg-gray-700 dark:border-gray-600">
    <div class="grid h-full max-w-lg grid-cols-3 mx-auto font-medium">
        <%= link_to looks_path, class: "inline-flex flex-col items-center justify-center px-5 hover:bg-gray-50 dark:hover:bg-gray-800 group" do %>
            <svg class="w-6 h-6 mb-1 text-gray-500 dark:text-gray-400 group-hover:text-blue-600 dark:group-hover:text-blue-500" fill="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path d="M12 2C9.243 2 7 4.243 7 7v4H4a1 1 0 00-1 1v9a1 1 0 001 1h16a1 1 0 001-1v-9a1 1 0 00-1-1h-3V7c0-2.757-2.243-5-5-5zm1 11h-2v-2h2v2zm-2-4V7c0-1.654 1.346-3 3-3s3 1.346 3 3v2H11zm-5 6h14v7H6v-7z"></path>
            </svg>
            <span class="text-sm text-gray-500 dark:text-gray-400 group-hover:text-blue-600 dark:group-hover:text-blue-500">Looks</span>
        <% end %>
        <button type="button" class="inline-flex flex-col items-center justify-center px-5 hover:bg-gray-50 dark:hover:bg-gray-800 group">
            <svg class="w-6 h-6 mb-1 text-gray-500 dark:text-gray-400 group-hover:text-blue-600 dark:group-hover:text-blue-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M6 1a1 1 0 00-1 1v1H4a2 2 0 00-2 2v11a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2h-1V2a1 1 0 10-2 0v1H7V2a1 1 0 00-1-1zm0 5a1 1 0 011 1v1a1 1 0 01-2 0V7a1 1 0 011-1zm4 0a1 1 0 011 1v1a1 1 0 01-2 0V7a1 1 0 011-1zm4 0a1 1 0 011 1v1a1 1 0 01-2 0V7a1 1 0 011-1z" clip-rule="evenodd"></path>
            </svg>
            <span class="text-sm text-gray-500 dark:text-gray-400 group-hover:text-blue-600 dark:group-hover:text-blue-500">Calendar</span>
        </button>
        <button type="button" class="inline-flex flex-col items-center justify-center px-5 hover:bg-gray-50 dark:hover:bg-gray-800 group">
            <svg class="w-6 h-6 mb-1 text-gray-500 dark:text-gray-400 group-hover:text-blue-600 dark:group-hover:text-blue-500" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path d="M10 4a4 4 0 100 8 4 4 0 000-8zm0 7a3 3 0 100-6 3 3 0 000 6zm-7 7a7 7 0 1114 0H3z"></path>
            </svg>
            <span class="text-sm text-gray-500 dark:text-gray-400 group-hover:text-blue-600 dark:group-hover:text-blue-500">Profile</span>
        </button>
    </div>
</div>

<%# <div class="fixed inset-x-0 bottom-0 bg-gray-800 text-white py-2 text-center shadow-md z-10">
    <%= link_to 'Looks', looks_path, class: "nav-link" %>
    <%# <%= link_to 'Calendar', "#", class: "nav-link" %> 
    <%# <%= link_to 'Profile', "#", class: "nav-link" %>
<%# </div> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShowroomApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-14 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/looks/_form.html.erb
<%= form_with model: @look, id: "new-look-form", data: {controller: "look", action: "turbo:submit-end->look#reset"} do |form| %>
  <% if @look.errors.any? %>
    <div id="error-explanation">
      <h2><%= pluralize(@look.errors.count, "error") %> prohibited this look from being saved:</h2>
      <ul>
        <% @look.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="close-btn">
    <%= link_to 'X', looks_path %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, required: true %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%# <%= form.file_field :photos, multiple: true, required: true, name: 'look[photos][]' %>
        <% @look.photos.each do |photo| %>
          <%= image_tag(url_for(photo), size: '100x100') %>
        <% end %>
    <%= form.file_field :photos, class: 'file-field', multiple: true, required: true, name: 'look[photos][]' %>
  </div>

  <div class="field">
    <%= form.label :category_names, "Categories" %>
    <%= form.text_field :category_names, value: @look.categories.map(&:name).join(', ') %>
    <p>Add categories separated by commas</p>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/looks/_look.html.erb
<div id="look_<%= look.id %>" class="look-card">
  <div class="categories">
      <% look.categories.each do |category| %>
        <span class="category"><%= category.name %></span>
      <% end %>
  </div>
  <div>
    <% look.photos.each do |photo| %>
      <%= image_tag(photo, class: '') %>
    <% end %>
  </div>
  <div class="actions">
    <%= link_to 'Edit look', edit_look_path(look), class: 'edit' %>
    <%= button_to 'Delete', look_path(look), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete' %>
  </div>
</div>

app/views/looks/create.turbo_stream.erb
<%= turbo_stream.append 'looks', @look %>

app/views/looks/edit.html.erb
<h2>Edit Look</h2>
<%= render 'form' %>
<%= link_to 'Cerrar', looks_path %>

app/views/looks/index.html.erb
<div class="container">
  <main>
    <title>
      <h1>Looks</h1>
    </title>
    <div class='filter'>
      <%= form_tag looks_path, method: :get do %>
        <%= label_tag :category_names, "Filter by Categories" %>
        <%= text_field_tag :category_names, params[:category_names], placeholder: "Enter categories separated by commas" %>
        <%= submit_tag "Filter" %>
        <%= link_to "Clear Filter", looks_path, class: "clear-filter" %>
      <% end %>
    </div>
    <div class="new-look-form-container">
      <%= turbo_frame_tag "new-look" do %>
        <%= link_to 'New Look', new_look_path(@look), class: 'main-btn', id: 'new-look-btn' %>
      <% end %>
    </div>
    <div id="looks">
      <% @looks.each do |look| %>
        <%= render 'look', look: look %>
      <% end %>
    </div>
  </main>
  <%= render 'layouts/nav' %>
</div>

app/views/looks/new.html.erb
<%= turbo_frame_tag "new-look" do %>  
    <%= render 'form' %>
<% end %>